name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_PW: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kazuhikotsuji/angular:latest
    - name: Push the Docker image
      run: |
        echo $DOCKER_PW | docker login --username $DOCKER_USER --password-stdin docker.io
        docker push docker.io/kazuhikotsuji/angular:latest