on: push
name: npm build, lint, test and publish
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install
        uses: actions/setup-node@v2
        with:
          args: install
      - name: npm test
        uses: actions/setup-node@v2
        with:
          args: run test
      - name: npm lint
        uses: actions/setup-node@v2
        with:
          args: run lint
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: kazuhikotsuji/angular
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}