on: push
name: npm build, lint, test and publish
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: npm install
        uses: actions/npm@master
        with:
          args: install
      - name: npm test
        uses: actions/npm@master
        with:
          args: run test
      - name: npm lint
        uses: actions/npm@master
        with:
          args: run lint
      - name: docker build
        uses: actions/docker/cli@master
        with:
          args: build -t kazuhikotsuji/angular .
      - name: docker login
        uses: actions/docker/login@master
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      - name: docker push
        uses: actions/docker/cli@master
        with:
          args: push kazuhikotsuji/angular